### ISSUE TITLE
code not appearing correctly

### ISSUE THREAD

**Issue by dearfrankg** [klugjo/hexo-theme-alpha-dust#1] opened 2016-08-02 19:29 UTC
blank lines do not appear correctly

**Comment by klugjo** [comment] 2016-08-03 02:29
Hi,

Can you provide a screenshot or live example of your problem ? I will look into it

Thanks

**Comment by dearfrankg** [comment] 2016-08-03 03:41
![screen](https://cloud.githubusercontent.com/assets/36104/17353107/7a9b04e0-58f1-11e6-9a28-c7cd924c63aa.png)

**Comment by dearfrankg** [comment] 2016-08-03 05:33
Multiline comments don't seem to work also...

    ```js
    var hi = function(name) {
      return 'Hi ' + name
    }

    /** ignorant
     * unnecessarily wraps a function
     * forces a one argument signature
     */
    var greeting = function(name) {
      return hi(name)
    }

    // enlightened
    var greeting = hi
    ```

![screen ml-comments](https://cloud.githubusercontent.com/assets/36104/17354867/220ba4d2-5901-11e6-8f38-824733062725.png)

**Comment by klugjo** [comment] 2016-08-04 00:30
I can't reproduce the issue, with your first example:

<img width="401" alt="screen shot 2016-08-04 at 8 23 18 am" src="https://cloud.githubusercontent.com/assets/2960040/17386414/1c6e4206-5a1d-11e6-9047-0e2de58cefb5.png">

For the Multiline problem, the issue comes from Hexo itself, more precisely the code highlighting engine they are using:

<img width="481" alt="screen shot 2016-08-04 at 8 28 18 am" src="https://cloud.githubusercontent.com/assets/2960040/17386444/729dc494-5a1d-11e6-9e50-8a352cd2dfc1.png">

**Comment by klugjo** [comment] 2016-08-04 00:31
Node version and npm packages versions ?

**Comment by dearfrankg** [comment] 2016-08-04 05:53
node: v5.10.1
npm: 3.8.3

    {
      "name": "hexo-site",
      "version": "0.0.0",
      "private": true,
      "hexo": {
        "version": "3.2.2"
      },
      "dependencies": {
        "hexo": "^3.2.0",
        "hexo-browsersync": "^0.2.0",
        "hexo-generator-archive": "^0.1.4",
        "hexo-generator-category": "^0.1.3",
        "hexo-generator-feed": "^1.2.0",
        "hexo-generator-index": "^0.2.0",
        "hexo-generator-sitemap": "^1.1.2",
        "hexo-generator-tag": "^0.2.0",
        "hexo-inject": "^1.0.0",
        "hexo-math": "^3.0.1",
        "hexo-renderer-ejs": "^0.2.0",
        "hexo-renderer-jade": "^0.3.0",
        "hexo-renderer-less": "^0.2.0",
        "hexo-renderer-marked": "^0.2.10",
        "hexo-renderer-sass": "^0.2.0",
        "hexo-renderer-stylus": "^0.3.1",
        "hexo-server": "^0.2.0",
        "hexo-tag-googlecharts": "^1.0.2"
      }
    }

## THEME: alpha-dust

![screen shot 2016-08-03 at 10 51 23 pm](https://cloud.githubusercontent.com/assets/36104/17391690/0d2d1f38-59cd-11e6-9dfc-34e27f83aaa9.png)


## THEME: again

![screen shot 2016-08-03 at 10 52 07 pm](https://cloud.githubusercontent.com/assets/36104/17391706/225da440-59cd-11e6-8ff3-24715e2919d8.png)

**Comment by dearfrankg** [comment] 2016-08-09 11:10
I ended up using the Jane theme.  Thanks for your efforts anyway.

**Comment by klugjo** [comment] 2016-09-05 02:58
This should be fixed by now. Closing this ticket.

**Closed by klugjo** 2016-09-05 02:58 UTC
