### ISSUE TITLE
many scroll bars in the code area.

### ISSUE THREAD

**Issue by CSGrandeur** [klugjo/hexo-theme-alpha-dust#4] opened 2016-08-29 12:13 UTC
\`\`\`
some code
\`\`\`

The web will display many ugly scroll bars in the code area.

![123](https://cloud.githubusercontent.com/assets/5326601/18051072/eedd7d0e-6e24-11e6-8864-ccf47ed5538c.png)

**Comment by klugjo** [comment] 2016-08-29 14:22
You are the second person to report this bug. Let me look into it. Will try to provide a fix in the next few days.

Can you send me your node version and hexo version ?

Thanks

**Comment by CSGrandeur** [comment] 2016-08-29 14:32
$ hexo -v
hexo: 3.2.2
hexo-cli: 1.0.2
os: Windows_NT 10.0.10586 win32 x64
http_parser: 2.7.0
node: 4.5.0
v8: 4.5.103.37
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h

**Comment by lisandro52** [comment] 2016-09-02 03:46
Hey @klugjo . I also noted this bug, and tried to fix it locally. What I did so far is remove the `overflow-x scroll !important` lines from the generated CSS (style.css [#468](https://github.com/klugjo/hexo-theme-alpha-dust/blob/master/template/css/style.css#L468) and [#475](https://github.com/klugjo/hexo-theme-alpha-dust/blob/master/template/css/style.css#L475)). I'm not sure why they're there but this does the trick.

**Comment by klugjo** [comment] 2016-09-04 13:33
Thanks @lisandro52 I noticed the same thing but was not sure as I can't reproduce the issue locally. It is displaying fine on Chrome, FF and Safari.

Anyways, I have done the modification. @CSGrandeur can you give it a shot when you have time ? Thanks

**Comment by CSGrandeur** [comment] 2016-09-04 14:07
@klugjo ,Year it wokrs~
![123](https://cloud.githubusercontent.com/assets/5326601/18231415/e9abc98c-72eb-11e6-86f2-eddd0bd9b932.png)

**Comment by klugjo** [comment] 2016-09-04 14:09
Awesome. Can you please verify that it also works when a line is longer than the width ? You should be able to scroll horizontally.

**Comment by CSGrandeur** [comment] 2016-09-04 15:35
OK
![456](https://cloud.githubusercontent.com/assets/5326601/18231979/3ac6b276-72f8-11e6-9273-dd5b40e7a437.png)

**Comment by klugjo** [comment] 2016-09-05 02:58
Great. Closing this.

**Closed by klugjo** 2016-09-05 02:58 UTC
Labels: bug
